set -g default-terminal "screen-256color"

# Set prefix to Ctrl + Space
set -g prefix C-Space
unbind C-b
bind-key C-Space send-prefix

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"


set -g mouse on

set-window-option -g mode-keys vi
